baseURL = 'https://knowwvana.github.io/knowwvana.learn/'
languageCode = 'en-us'
title = 'Knowwvana Learn'
enableGitInfo = true

[params]
  brand = "Knowvaana"
  tagline = "A living wiki of knowledge & experiments"